INSERT INTO roles (name)
VALUES ('ROLE_USER'),('ROLE_MODERATOR'),('ROLE_ADMIN');



/*
INSERT INTO roles (name)
SELECT 'ROLE_USER' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM roles WHERE name='ROLE_USER' LIMIT 1)

INSERT INTO roles (name)
SELECT 'ROLE_MODERATOR' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM roles WHERE name='ROLE_MODERATOR' LIMIT 1)

INSERT INTO roles (name)
SELECT 'ROLE_ADMIN' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM roles WHERE name='ROLE_ADMIN' LIMIT 1)
*/

